from __future__ import annotations

import json
import logging
from collections.abc import Iterable, Mapping
from typing import Any

from django.conf import settings
from django.core.cache import cache
from django.http import HttpRequest, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_GET, require_POST

from support.services.gorgias import GorgiasAPIError
from support.services.processor import SupportTicketProcessor

logger = logging.getLogger(__name__)

TICKET_ID_KEYS = {"ticket_id", "ticketid", "gorgias_ticket_id"}
EVENT_ID_KEYS = {"event_id", "eventid", "webhook_id", "webhookid"}
LOOP_MARKERS = ("generated by demo ai automation",)


@require_GET
def health(request: HttpRequest) -> JsonResponse:
    return JsonResponse({"status": "ok"})


@csrf_exempt
@require_POST
def gorgias_webhook(request: HttpRequest) -> JsonResponse:
    try:
        payload = json.loads(request.body.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError):
        return JsonResponse({"error": "Invalid JSON payload."}, status=400)

    if not isinstance(payload, dict):
        return JsonResponse({"error": "Payload must be a JSON object."}, status=400)

    ticket_id = extract_ticket_id(payload)
    if not ticket_id:
        return JsonResponse({"error": "Could not extract a Gorgias ticket ID."}, status=400)

    event_id = extract_event_id(payload)
    idempotency_key = f"gorgias-webhook:{event_id}" if event_id else ""
    if idempotency_key and cache.get(idempotency_key):
        return JsonResponse(
            {"status": "ignored", "reason": "duplicate_event", "ticket_id": ticket_id}
        )

    if is_integration_generated_event(payload):
        if idempotency_key:
            cache.set(idempotency_key, "ignored", settings.WEBHOOK_IDEMPOTENCY_TTL_SECONDS)
        logger.info("Ignored integration-generated Gorgias event for ticket %s.", ticket_id)
        return JsonResponse(
            {"status": "ignored", "reason": "integration_loop", "ticket_id": ticket_id}
        )

    try:
        result = SupportTicketProcessor().process(ticket_id, payload)
    except GorgiasAPIError as exc:
        logger.warning("Gorgias processing failed for ticket %s: %s", ticket_id, exc)
        return JsonResponse(
            {"error": "Could not process ticket through Gorgias.", "ticket_id": ticket_id},
            status=502,
        )

    if idempotency_key:
        cache.set(idempotency_key, "processed", settings.WEBHOOK_IDEMPOTENCY_TTL_SECONDS)

    return JsonResponse(
        {
            "status": "processed",
            "ticket_id": result.ticket_id,
            "priority": result.decision.priority,
            "recommended_action": result.decision.recommended_action,
            "human_review_required": result.decision.human_review_required,
            "customer_message_sent": False,
        }
    )


def extract_ticket_id(payload: Mapping[str, Any]) -> str | None:
    direct_value = _first_matching_value(payload, TICKET_ID_KEYS)
    if direct_value:
        return direct_value

    for key in ("ticket", "ticket_data"):
        value = payload.get(key)
        if isinstance(value, Mapping):
            ticket_id = _clean_id(value.get("id"))
            if ticket_id:
                return ticket_id

    object_type = str(payload.get("object_type") or payload.get("type") or "").lower()
    if "ticket" in object_type:
        ticket_id = _clean_id(payload.get("object_id") or payload.get("objectId"))
        if ticket_id:
            return ticket_id

    for value in payload.values():
        if isinstance(value, Mapping):
            ticket_id = extract_ticket_id(value)
            if ticket_id:
                return ticket_id
        elif isinstance(value, list):
            for item in value:
                if isinstance(item, Mapping):
                    ticket_id = extract_ticket_id(item)
                    if ticket_id:
                        return ticket_id
    return None


def extract_event_id(payload: Mapping[str, Any]) -> str | None:
    return _first_matching_value(payload, EVENT_ID_KEYS)


def is_integration_generated_event(payload: Mapping[str, Any]) -> bool:
    integration_name = settings.INTEGRATION_NAME.strip().lower()
    configured_email = settings.GORGIAS_INTEGRATION_EMAIL.strip().lower()
    configured_user_id = settings.GORGIAS_INTEGRATION_USER_ID.strip()

    for key, value in _walk_scalars(payload):
        key_text = key.lower()
        value_text = str(value).strip().lower()
        if key_text in {"from_agent", "from_self", "generated_by_integration"} and value is True:
            return True
        if any(marker in value_text for marker in LOOP_MARKERS):
            return True
        if integration_name and key_text in {"app", "app_name", "integration", "source"}:
            if integration_name in value_text:
                return True
        if configured_email and key_text == "email" and value_text == configured_email:
            return True
        if configured_user_id and key_text in {"id", "user_id", "sender_id"}:
            if str(value).strip() == configured_user_id:
                return True
    return False


def _first_matching_value(payload: Mapping[str, Any], keys: Iterable[str]) -> str | None:
    normalized_keys = {key.lower() for key in keys}
    for key, value in payload.items():
        if str(key).lower() in normalized_keys:
            clean_value = _clean_id(value)
            if clean_value:
                return clean_value
    return None


def _clean_id(value: Any) -> str | None:
    if value is None:
        return None
    if isinstance(value, bool):
        return None
    text = str(value).strip()
    if not text:
        return None
    return text


def _walk_scalars(obj: Any, parent_key: str = "") -> Iterable[tuple[str, Any]]:
    if isinstance(obj, Mapping):
        for key, value in obj.items():
            yield from _walk_scalars(value, str(key))
    elif isinstance(obj, list):
        for item in obj:
            yield from _walk_scalars(item, parent_key)
    else:
        yield parent_key, obj
