from __future__ import annotations

import json
from types import SimpleNamespace

from support.services.gorgias import GorgiasAPIError


def test_health_endpoint(client) -> None:
    response = client.get("/health/")

    assert response.status_code == 200
    assert response.json() == {"status": "ok"}


def test_valid_webhook_processes_ticket(client, monkeypatch) -> None:
    class FakeProcessor:
        def process(self, ticket_id, payload):
            assert ticket_id == "12345"
            assert payload["ticket_id"] == 12345
            return SimpleNamespace(
                ticket_id=ticket_id,
                decision=SimpleNamespace(
                    priority="low",
                    recommended_action="agent_review",
                    human_review_required=True,
                ),
            )

    monkeypatch.setattr("support.views.SupportTicketProcessor", FakeProcessor)

    response = client.post(
        "/api/webhooks/gorgias/",
        data=json.dumps({"event_id": "evt-valid", "ticket_id": 12345}),
        content_type="application/json",
    )

    assert response.status_code == 200
    assert response.json()["status"] == "processed"
    assert response.json()["customer_message_sent"] is False


def test_malformed_webhook_returns_400(client) -> None:
    response = client.post(
        "/api/webhooks/gorgias/",
        data="{not-json",
        content_type="application/json",
    )

    assert response.status_code == 400
    assert response.json()["error"] == "Invalid JSON payload."


def test_gorgias_api_failure_returns_502(client, monkeypatch) -> None:
    class FakeProcessor:
        def process(self, ticket_id, payload):
            raise GorgiasAPIError("upstream failed")

    monkeypatch.setattr("support.views.SupportTicketProcessor", FakeProcessor)

    response = client.post(
        "/api/webhooks/gorgias/",
        data=json.dumps({"ticket": {"id": 987}}),
        content_type="application/json",
    )

    assert response.status_code == 502
    assert response.json()["ticket_id"] == "987"


def test_webhook_loop_prevention_ignores_integration_events(client, monkeypatch) -> None:
    class ExplodingProcessor:
        def process(self, ticket_id, payload):
            raise AssertionError("processor should not be called")

    monkeypatch.setattr("support.views.SupportTicketProcessor", ExplodingProcessor)

    response = client.post(
        "/api/webhooks/gorgias/",
        data=json.dumps(
            {
                "ticket_id": 222,
                "message": {
                    "from_agent": True,
                    "body_text": "Generated by demo AI automation.",
                },
            }
        ),
        content_type="application/json",
    )

    assert response.status_code == 200
    assert response.json()["status"] == "ignored"
    assert response.json()["reason"] == "integration_loop"
